# Generated by Django 3.1.7 on 2021-05-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rain_forecast', '0003_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rain_forecast.device')),
                ('type', models.CharField(choices=[('RS', 'rain sensor'), ('TS', 'temperature sensor'), ('WS', 'wind sensor')], default='RS', max_length=2)),
            ],
        ),
    ]
