# Generated by Django 3.1.7 on 2021-05-20 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rain_forecast', '0004_device_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='register_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rain_forecast.user'),
        ),
    ]
