# Generated by Django 3.1.7 on 2021-06-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rain_forecast', '0007_auto_20210610_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='No title', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
